import React from 'react';

import Psalm1 from '../../../pages/Psalm1';
import Psalm2 from '../../../pages/Psalm2';
import Psalm3 from '../../../pages/Psalm3';
import Psalm4 from '../../../pages/Psalm4';
import Psalm5 from '../../../pages/Psalm5';
import Psalm6 from '../../../pages/Psalm6';
import Psalm7 from '../../../pages/Psalm7';
import Psalm8 from '../../../pages/Psalm8';
import Psalm9 from '../../../pages/Psalm9';
import Psalm10 from '../../../pages/Psalm10';
import Psalm11 from '../../../pages/Psalm11';
import Psalm12 from '../../../pages/Psalm12';
import Psalm13 from '../../../pages/Psalm13';
import Psalm14 from '../../../pages/Psalm14';
import Psalm15 from '../../../pages/Psalm15';
import Psalm16 from '../../../pages/Psalm16';
import Psalm17 from '../../../pages/Psalm17';
import Psalm18 from '../../../pages/Psalm18';
import Psalm19 from '../../../pages/Psalm19';
import Psalm20 from '../../../pages/Psalm20';
import Psalm21 from '../../../pages/Psalm21';
import Psalm22 from '../../../pages/Psalm22';
import Psalm23 from '../../../pages/Psalm23';
import Psalm24 from '../../../pages/Psalm24';
import Psalm25 from '../../../pages/Psalm25';
import Psalm26 from '../../../pages/Psalm26';
import Psalm27 from '../../../pages/Psalm27';
import Psalm28 from '../../../pages/Psalm28';
import Psalm29 from '../../../pages/Psalm29';
import Psalm30 from '../../../pages/Psalm30';
import Psalm31 from '../../../pages/Psalm31';
import Psalm32 from '../../../pages/Psalm32';
import Psalm33 from '../../../pages/Psalm33';
import Psalm34 from '../../../pages/Psalm34';
import Psalm35 from '../../../pages/Psalm35';
import Psalm36 from '../../../pages/Psalm36';
import Psalm37 from '../../../pages/Psalm37';
import Psalm38 from '../../../pages/Psalm38';
import Psalm39 from '../../../pages/Psalm39';
import Psalm40 from '../../../pages/Psalm40';
import Psalm41 from '../../../pages/Psalm41';
import Psalm42 from '../../../pages/Psalm42';
import Psalm43 from '../../../pages/Psalm43';
import Psalm44 from '../../../pages/Psalm44';
import Psalm45 from '../../../pages/Psalm45';
import Psalm46 from '../../../pages/Psalm46';
import Psalm47 from '../../../pages/Psalm47';
import Psalm48 from '../../../pages/Psalm48';
import Psalm49 from '../../../pages/Psalm49';
import Psalm50 from '../../../pages/Psalm50';
import Psalm51 from '../../../pages/Psalm51';
import Psalm52 from '../../../pages/Psalm52';
import Psalm53 from '../../../pages/Psalm53';
import Psalm54 from '../../../pages/Psalm54';
import Psalm55 from '../../../pages/Psalm55';
import Psalm56 from '../../../pages/Psalm56';
import Psalm57 from '../../../pages/Psalm57';
import Psalm58 from '../../../pages/Psalm58';
import Psalm59 from '../../../pages/Psalm59';
import Psalm60 from '../../../pages/Psalm60';
import Psalm61 from '../../../pages/Psalm61';
import Psalm62 from '../../../pages/Psalm62';
import Psalm63 from '../../../pages/Psalm63';
import Psalm64 from '../../../pages/Psalm64';
import Psalm65 from '../../../pages/Psalm65';
import Psalm66 from '../../../pages/Psalm66';
import Psalm67 from '../../../pages/Psalm67';
import Psalm68 from '../../../pages/Psalm68';
import Psalm69 from '../../../pages/Psalm69';
import Psalm70 from '../../../pages/Psalm70';
import Psalm71 from '../../../pages/Psalm71';
import Psalm72 from '../../../pages/Psalm72';
import Psalm73 from '../../../pages/Psalm73';
import Psalm74 from '../../../pages/Psalm74';
import Psalm75 from '../../../pages/Psalm75';
import Psalm76 from '../../../pages/Psalm76';
import Psalm77 from '../../../pages/Psalm77';
import Psalm78 from '../../../pages/Psalm78';
import Psalm79 from '../../../pages/Psalm79';
import Psalm80 from '../../../pages/Psalm80';
import Psalm81 from '../../../pages/Psalm81';
import Psalm82 from '../../../pages/Psalm82';
import Psalm83 from '../../../pages/Psalm83';
import Psalm84 from '../../../pages/Psalm84';
import Psalm85 from '../../../pages/Psalm85';
import Psalm86 from '../../../pages/Psalm86';
import Psalm87 from '../../../pages/Psalm87';
import Psalm88 from '../../../pages/Psalm88';
import Psalm89 from '../../../pages/Psalm89';
import Psalm90 from '../../../pages/Psalm90';
import Psalm91 from '../../../pages/Psalm91';
import Psalm92 from '../../../pages/Psalm92';
import Psalm93 from '../../../pages/Psalm93';
import Psalm94 from '../../../pages/Psalm94';
import Psalm95 from '../../../pages/Psalm95';
import Psalm96 from '../../../pages/Psalm96';
import Psalm97 from '../../../pages/Psalm97';
import Psalm98 from '../../../pages/Psalm98';
import Psalm99 from '../../../pages/Psalm99';
import Psalm100 from '../../../pages/Psalm100';
import Psalm101 from '../../../pages/Psalm101';
import Psalm102 from '../../../pages/Psalm102';
import Psalm103 from '../../../pages/Psalm103';
import Psalm104 from '../../../pages/Psalm104';
import Psalm105 from '../../../pages/Psalm105';
import Psalm106 from '../../../pages/Psalm106';
import Psalm107 from '../../../pages/Psalm107';
import Psalm108 from '../../../pages/Psalm108';
import Psalm109 from '../../../pages/Psalm109';
import Psalm110 from '../../../pages/Psalm110';
import Psalm111 from '../../../pages/Psalm111';
import Psalm112 from '../../../pages/Psalm112';
import Psalm113 from '../../../pages/Psalm113';
import Psalm114 from '../../../pages/Psalm114';
import Psalm115 from '../../../pages/Psalm115';
import Psalm116 from '../../../pages/Psalm116';
import Psalm117 from '../../../pages/Psalm117';
import Psalm118 from '../../../pages/Psalm118';
import Psalm119 from '../../../pages/Psalm119';
import Psalm120 from '../../../pages/Psalm120';
import Psalm121 from '../../../pages/Psalm121';
import Psalm122 from '../../../pages/Psalm122';
import Psalm123 from '../../../pages/Psalm123';
import Psalm124 from '../../../pages/Psalm124';
import Psalm125 from '../../../pages/Psalm125';
import Psalm126 from '../../../pages/Psalm126';
import Psalm127 from '../../../pages/Psalm127';
import Psalm128 from '../../../pages/Psalm128';
import Psalm129 from '../../../pages/Psalm129';
import Psalm130 from '../../../pages/Psalm130';
import Psalm131 from '../../../pages/Psalm131';
import Psalm132 from '../../../pages/Psalm132';
import Psalm133 from '../../../pages/Psalm133';
import Psalm134 from '../../../pages/Psalm134';
import Psalm135 from '../../../pages/Psalm135';
import Psalm136 from '../../../pages/Psalm136';
import Psalm137 from '../../../pages/Psalm137';
import Psalm138 from '../../../pages/Psalm138';
import Psalm139 from '../../../pages/Psalm139';
import Psalm140 from '../../../pages/Psalm140';
import Psalm141 from '../../../pages/Psalm141';
import Psalm142 from '../../../pages/Psalm142';
import Psalm143 from '../../../pages/Psalm143';
import Psalm144 from '../../../pages/Psalm144';
import Psalm145 from '../../../pages/Psalm145';
import Psalm146 from '../../../pages/Psalm146';
import Psalm147 from '../../../pages/Psalm147';
import Psalm148 from '../../../pages/Psalm148';
import Psalm149 from '../../../pages/Psalm149';
import Psalm150 from '../../../pages/Psalm150';


export const getPsalmToDisplay = componentProps => {
  const idOfPsalmToDisplay = componentProps.match.params.psalmId;
  //const nameOfPsalmToDisplay = componentProps.match.params.psalmName;

  if (idOfPsalmToDisplay === '1') return <Psalm1 />;
  if (idOfPsalmToDisplay === '2') return <Psalm2 />;
  if (idOfPsalmToDisplay === '3') return <Psalm3 />;
  if (idOfPsalmToDisplay === '4') return <Psalm4 />;
  if (idOfPsalmToDisplay === '5') return <Psalm5 />;
  if (idOfPsalmToDisplay === '6') return <Psalm6 />;
  if (idOfPsalmToDisplay === '7') return <Psalm7 />;
  if (idOfPsalmToDisplay === '8') return <Psalm8 />;
  if (idOfPsalmToDisplay === '9') return <Psalm9 />;
  if (idOfPsalmToDisplay === '10') return <Psalm10 />;
  if (idOfPsalmToDisplay === '11') return <Psalm11 />;
  if (idOfPsalmToDisplay === '12') return <Psalm12 />;
  if (idOfPsalmToDisplay === '13') return <Psalm13 />;
  if (idOfPsalmToDisplay === '14') return <Psalm14 />;
  if (idOfPsalmToDisplay === '15') return <Psalm15 />;
  if (idOfPsalmToDisplay === '16') return <Psalm16 />;
  if (idOfPsalmToDisplay === '17') return <Psalm17 />;
  if (idOfPsalmToDisplay === '18') return <Psalm18 />;
  if (idOfPsalmToDisplay === '19') return <Psalm19 />;
  if (idOfPsalmToDisplay === '20') return <Psalm20 />;
  if (idOfPsalmToDisplay === '21') return <Psalm21 />;
  if (idOfPsalmToDisplay === '22') return <Psalm22 />;
  if (idOfPsalmToDisplay === '23') return <Psalm23 />;
  if (idOfPsalmToDisplay === '24') return <Psalm24 />;
  if (idOfPsalmToDisplay === '25') return <Psalm25 />;
  if (idOfPsalmToDisplay === '26') return <Psalm26 />;
  if (idOfPsalmToDisplay === '27') return <Psalm27 />;
  if (idOfPsalmToDisplay === '28') return <Psalm28 />;
  if (idOfPsalmToDisplay === '29') return <Psalm29 />;
  if (idOfPsalmToDisplay === '30') return <Psalm30 />;
  if (idOfPsalmToDisplay === '31') return <Psalm31 />;
  if (idOfPsalmToDisplay === '32') return <Psalm32 />;
  if (idOfPsalmToDisplay === '33') return <Psalm33 />;
  if (idOfPsalmToDisplay === '34') return <Psalm34 />;
  if (idOfPsalmToDisplay === '35') return <Psalm35 />;
  if (idOfPsalmToDisplay === '36') return <Psalm36 />;
  if (idOfPsalmToDisplay === '37') return <Psalm37 />;
  if (idOfPsalmToDisplay === '38') return <Psalm38 />;
  if (idOfPsalmToDisplay === '39') return <Psalm39 />;
  if (idOfPsalmToDisplay === '40') return <Psalm40 />;
  if (idOfPsalmToDisplay === '41') return <Psalm41 />;
  if (idOfPsalmToDisplay === '42') return <Psalm42 />;
  if (idOfPsalmToDisplay === '43') return <Psalm43 />;
  if (idOfPsalmToDisplay === '44') return <Psalm44 />;
  if (idOfPsalmToDisplay === '45') return <Psalm45 />;
  if (idOfPsalmToDisplay === '46') return <Psalm46 />;
  if (idOfPsalmToDisplay === '47') return <Psalm47 />;
  if (idOfPsalmToDisplay === '48') return <Psalm48 />;
  if (idOfPsalmToDisplay === '49') return <Psalm49 />;
  if (idOfPsalmToDisplay === '50') return <Psalm50 />;
  if (idOfPsalmToDisplay === '51') return <Psalm51 />;
  if (idOfPsalmToDisplay === '52') return <Psalm52 />;
  if (idOfPsalmToDisplay === '53') return <Psalm53 />;
  if (idOfPsalmToDisplay === '54') return <Psalm54 />;
  if (idOfPsalmToDisplay === '55') return <Psalm55 />;
  if (idOfPsalmToDisplay === '56') return <Psalm56 />;
  if (idOfPsalmToDisplay === '57') return <Psalm57 />;
  if (idOfPsalmToDisplay === '58') return <Psalm58 />;
  if (idOfPsalmToDisplay === '59') return <Psalm59 />;
  if (idOfPsalmToDisplay === '60') return <Psalm60 />;
  if (idOfPsalmToDisplay === '61') return <Psalm61 />;
  if (idOfPsalmToDisplay === '62') return <Psalm62 />;
  if (idOfPsalmToDisplay === '63') return <Psalm63 />;
  if (idOfPsalmToDisplay === '64') return <Psalm64 />;
  if (idOfPsalmToDisplay === '65') return <Psalm65 />;
  if (idOfPsalmToDisplay === '66') return <Psalm66 />;
  if (idOfPsalmToDisplay === '67') return <Psalm67 />;
  if (idOfPsalmToDisplay === '68') return <Psalm68 />;
  if (idOfPsalmToDisplay === '69') return <Psalm69 />;
  if (idOfPsalmToDisplay === '70') return <Psalm70 />;
  if (idOfPsalmToDisplay === '71') return <Psalm71 />;
  if (idOfPsalmToDisplay === '72') return <Psalm72 />;
  if (idOfPsalmToDisplay === '73') return <Psalm73 />;
  if (idOfPsalmToDisplay === '74') return <Psalm74 />;
  if (idOfPsalmToDisplay === '75') return <Psalm75 />;
  if (idOfPsalmToDisplay === '76') return <Psalm76 />;
  if (idOfPsalmToDisplay === '77') return <Psalm77 />;
  if (idOfPsalmToDisplay === '78') return <Psalm78 />;
  if (idOfPsalmToDisplay === '79') return <Psalm79 />;
  if (idOfPsalmToDisplay === '80') return <Psalm80 />;
  if (idOfPsalmToDisplay === '81') return <Psalm81 />;
  if (idOfPsalmToDisplay === '82') return <Psalm82 />;
  if (idOfPsalmToDisplay === '83') return <Psalm83 />;
  if (idOfPsalmToDisplay === '84') return <Psalm84 />;
  if (idOfPsalmToDisplay === '85') return <Psalm85 />;
  if (idOfPsalmToDisplay === '86') return <Psalm86 />;
  if (idOfPsalmToDisplay === '87') return <Psalm87 />;
  if (idOfPsalmToDisplay === '88') return <Psalm88 />;
  if (idOfPsalmToDisplay === '89') return <Psalm89 />;
  if (idOfPsalmToDisplay === '90') return <Psalm90 />;
  if (idOfPsalmToDisplay === '91') return <Psalm91 />;
  if (idOfPsalmToDisplay === '92') return <Psalm92 />;
  if (idOfPsalmToDisplay === '93') return <Psalm93 />;
  if (idOfPsalmToDisplay === '94') return <Psalm94 />;
  if (idOfPsalmToDisplay === '95') return <Psalm95 />;
  if (idOfPsalmToDisplay === '96') return <Psalm96 />;
  if (idOfPsalmToDisplay === '97') return <Psalm97 />;
  if (idOfPsalmToDisplay === '98') return <Psalm98 />;
  if (idOfPsalmToDisplay === '99') return <Psalm99 />;
  if (idOfPsalmToDisplay === '100') return <Psalm100 />;
  if (idOfPsalmToDisplay === '101') return <Psalm101 />;
  if (idOfPsalmToDisplay === '102') return <Psalm102 />;
  if (idOfPsalmToDisplay === '103') return <Psalm103 />;
  if (idOfPsalmToDisplay === '104') return <Psalm104 />;
  if (idOfPsalmToDisplay === '105') return <Psalm105 />;
  if (idOfPsalmToDisplay === '106') return <Psalm106 />;
  if (idOfPsalmToDisplay === '107') return <Psalm107 />;
  if (idOfPsalmToDisplay === '108') return <Psalm108 />;
  if (idOfPsalmToDisplay === '109') return <Psalm109 />;
  if (idOfPsalmToDisplay === '110') return <Psalm110 />;
  if (idOfPsalmToDisplay === '111') return <Psalm111 />;
  if (idOfPsalmToDisplay === '112') return <Psalm112 />;
  if (idOfPsalmToDisplay === '113') return <Psalm113 />;
  if (idOfPsalmToDisplay === '114') return <Psalm114 />;
  if (idOfPsalmToDisplay === '115') return <Psalm115 />;
  if (idOfPsalmToDisplay === '116') return <Psalm116 />;
  if (idOfPsalmToDisplay === '117') return <Psalm117 />;
  if (idOfPsalmToDisplay === '118') return <Psalm118 />;
  if (idOfPsalmToDisplay === '119') return <Psalm119 />;
  if (idOfPsalmToDisplay === '120') return <Psalm120 />;
  if (idOfPsalmToDisplay === '121') return <Psalm121 />;
  if (idOfPsalmToDisplay === '122') return <Psalm122 />;
  if (idOfPsalmToDisplay === '123') return <Psalm123 />;
  if (idOfPsalmToDisplay === '124') return <Psalm124 />;
  if (idOfPsalmToDisplay === '125') return <Psalm125 />;
  if (idOfPsalmToDisplay === '126') return <Psalm126 />;
  if (idOfPsalmToDisplay === '127') return <Psalm127 />;
  if (idOfPsalmToDisplay === '128') return <Psalm128 />;
  if (idOfPsalmToDisplay === '129') return <Psalm129 />;
  if (idOfPsalmToDisplay === '130') return <Psalm130 />;
  if (idOfPsalmToDisplay === '131') return <Psalm131 />;
  if (idOfPsalmToDisplay === '132') return <Psalm132 />;
  if (idOfPsalmToDisplay === '133') return <Psalm133 />;
  if (idOfPsalmToDisplay === '134') return <Psalm134 />;
  if (idOfPsalmToDisplay === '135') return <Psalm135 />;
  if (idOfPsalmToDisplay === '136') return <Psalm136 />;
  if (idOfPsalmToDisplay === '137') return <Psalm137 />;
  if (idOfPsalmToDisplay === '138') return <Psalm138 />;
  if (idOfPsalmToDisplay === '139') return <Psalm139 />;
  if (idOfPsalmToDisplay === '140') return <Psalm140 />;
  if (idOfPsalmToDisplay === '141') return <Psalm141 />;
  if (idOfPsalmToDisplay === '142') return <Psalm142 />;
  if (idOfPsalmToDisplay === '143') return <Psalm143 />;
  if (idOfPsalmToDisplay === '144') return <Psalm144 />;
  if (idOfPsalmToDisplay === '145') return <Psalm145 />;
  if (idOfPsalmToDisplay === '146') return <Psalm146 />;
  if (idOfPsalmToDisplay === '147') return <Psalm147 />;
  if (idOfPsalmToDisplay === '148') return <Psalm148 />;
  if (idOfPsalmToDisplay === '149') return <Psalm149 />;
  if (idOfPsalmToDisplay === '150') return <Psalm150 />;
}